version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: myapi_clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_USER: "${CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICHOUSE_DB: "${CLICKHOUSE_DB}"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./_docker-data/clickhouse/lib:/var/lib/clickhouse
      - ./_docker-data/clickhouse/logs:/var/log/clickhouse-server
  redis:
    image: redis
    container_name: myapi-redis
    ports:
      - 6379:6379
    volumes:
      - ./_docker-data/redis:/data
      - ./script/redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure
    networks:
      - myapi-network

networks:
  myapi-network: